# MPLAB IDE generated this makefile for use with GNU make.
# Project: Ostanovki.mcp
# Date: Sat Sep 25 14:38:18 2010

AS = pic30-as.exe
CC = pic30-gcc.exe
LD = pic30-ld.exe
AR = pic30-ar.exe
HX = pic30-bin2hex.exe
RM = rm

Ostanovki.hex : Ostanovki.cof
	$(HX) "Ostanovki.cof"

Ostanovki.cof : Ostanovki.o FSIO.o osa.o SD-SPI.o DEE\ Emulation\ 16-bit.o Flash\ Operations.o
	$(CC) -mcpu=24FJ64GA002 "Ostanovki.o" "FSIO.o" "osa.o" "SD-SPI.o" "DEE Emulation 16-bit.o" "Flash Operations.o" "C:\Program Files\Microchip\MPLAB C30\lib\PIC24F\libpPIC24Fxxx-coff.a" -o"Ostanovki.cof" -Wl,-Tp24FJ64GA002.gld,--defsym=__MPLAB_BUILD=1,-Map="Ostanovki.map",--report-mem

Ostanovki.o : DEE\ Emulation\ 16-bit.h lcd.h lcd.c time.c C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSDefs.h FSconfig.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/SD-SPI.h c:/program\ files/microchip/mplab\ c30/include/stddef.h C:/Microchip\ Solutions/Microchip/Include/GenericTypeDefs.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSDefs.h C:/Microchip\ Solutions/Microchip/Include/uart2.h HardwareProfile.h c:/program\ files/microchip/mplab\ c30/include/string.h c:/program\ files/microchip/mplab\ c30/include/stdlib.h c:/program\ files/microchip/mplab\ c30/include/stdio.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24FJ64GA002.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24Fxxxx.h C:/Microchip\ Solutions/Microchip/Include/Compiler.h FSconfig.h c:/program\ files/microchip/mplab\ c30/include/stddef.h C:/Microchip\ Solutions/Microchip/Include/GenericTypeDefs.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSIO.h C:/osa/service/osa_timer.h C:/osa/service/osa_tasks.h C:/osa/service/osa_smsg.h C:/osa/service/osa_squeue.h C:/osa/service/osa_queue.h C:/osa/service/osa_msg.h C:/osa/service/osa_qtimer.h C:/osa/service/osa_dtimer.h C:/osa/service/osa_stimer_old.h C:/osa/service/osa_stimer.h C:/osa/service/osa_flag.h C:/osa/service/osa_csem.h C:/osa/service/osa_bsem.h C:/osa/service/osa_system.h C:/osa/service/osa_oldnames.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24FJ64GA002.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24Fxxxx.h C:/osa/port/osa_mcc30.h C:/osa/port/osa_include.h OSAcfg.h C:/osa/osa.h c:/program\ files/microchip/mplab\ c30/include/math.h c:/program\ files/microchip/mplab\ c30/include/stdlib.h c:/program\ files/microchip/mplab\ c30/include/ctype.h c:/program\ files/microchip/mplab\ c30/include/stdio.h c:/program\ files/microchip/mplab\ c30/include/yvals.h c:/program\ files/microchip/mplab\ c30/include/string.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24FJ64GA002.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24Fxxxx.h Ostanovki.c
	$(CC) -mcpu=24FJ64GA002 -x c -c "Ostanovki.c" -o"Ostanovki.o" -I"C:\Microchip Solutions\Microchip\Include\MDD File System" -I"C:\Microchip Solutions\Microchip\Include" -I"D:\Projects C\Ostanovki" -I"C:\osa" -g -fno-short-double -Wall

FSIO.o : C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSDefs.h c:/program\ files/microchip/mplab\ c30/include/ctype.h c:/program\ files/microchip/mplab\ c30/include/stdlib.h c:/program\ files/microchip/mplab\ c30/include/string.h C:/Microchip\ Solutions/Microchip/Include/GenericTypeDefs.h FSconfig.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/SD-SPI.h c:/program\ files/microchip/mplab\ c30/include/stddef.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSDefs.h C:/Microchip\ Solutions/Microchip/Include/uart2.h HardwareProfile.h C:/Microchip\ Solutions/Microchip/Include/Compiler.h FSconfig.h c:/program\ files/microchip/mplab\ c30/include/stddef.h C:/Microchip\ Solutions/Microchip/Include/GenericTypeDefs.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSIO.h c:/program\ files/microchip/mplab\ c30/include/string.h c:/program\ files/microchip/mplab\ c30/include/stdlib.h c:/program\ files/microchip/mplab\ c30/include/yvals.h c:/program\ files/microchip/mplab\ c30/include/stdio.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24FJ64GA002.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24Fxxxx.h C:/Microchip\ Solutions/Microchip/Include/Compiler.h C:/Microchip\ Solutions/Microchip/MDD\ File\ System/FSIO.c
	$(CC) -mcpu=24FJ64GA002 -x c -c "C:\Microchip Solutions\Microchip\MDD File System\FSIO.c" -o"FSIO.o" -I"C:\Microchip Solutions\Microchip\Include\MDD File System" -I"C:\Microchip Solutions\Microchip\Include" -I"D:\Projects C\Ostanovki" -I"C:\osa" -g -fno-short-double -Wall

osa.o : C:/osa/service/osa_tasks.c C:/osa/service/osa_system.c C:/osa/service/osa_csem.c C:/osa/service/osa_queue.c C:/osa/service/osa_squeue.c C:/osa/service/osa_stimer.c C:/osa/service/osa_qtimer.c C:/osa/service/osa_dtimer.c C:/osa/port/osa_mcc30.c C:/osa/port/osa_include.c C:/osa/service/osa_timer.h C:/osa/service/osa_tasks.h C:/osa/service/osa_smsg.h C:/osa/service/osa_squeue.h C:/osa/service/osa_queue.h C:/osa/service/osa_msg.h C:/osa/service/osa_qtimer.h C:/osa/service/osa_dtimer.h C:/osa/service/osa_stimer_old.h C:/osa/service/osa_stimer.h C:/osa/service/osa_flag.h C:/osa/service/osa_csem.h C:/osa/service/osa_bsem.h C:/osa/service/osa_system.h C:/osa/service/osa_oldnames.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24FJ64GA002.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24Fxxxx.h C:/osa/port/osa_mcc30.h C:/osa/port/osa_include.h OSAcfg.h C:/osa/OSA.h C:/osa/osa.c
	$(CC) -mcpu=24FJ64GA002 -x c -c "C:\osa\osa.c" -o"osa.o" -I"C:\Microchip Solutions\Microchip\Include\MDD File System" -I"C:\Microchip Solutions\Microchip\Include" -I"D:\Projects C\Ostanovki" -I"C:\osa" -g -fno-short-double -Wall

SD-SPI.o : HardwareProfile.h FSConfig.h c:/program\ files/microchip/mplab\ c30/include/string.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/SD-SPI.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSDefs.h FSconfig.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/SD-SPI.h c:/program\ files/microchip/mplab\ c30/include/stddef.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSDefs.h C:/Microchip\ Solutions/Microchip/Include/uart2.h HardwareProfile.h C:/Microchip\ Solutions/Microchip/Include/Compiler.h FSconfig.h C:/Microchip\ Solutions/Microchip/Include/GenericTypeDefs.h C:/Microchip\ Solutions/Microchip/Include/MDD\ File\ System/FSIO.h c:/program\ files/microchip/mplab\ c30/include/stddef.h C:/Microchip\ Solutions/Microchip/Include/GenericTypeDefs.h c:/program\ files/microchip/mplab\ c30/include/string.h c:/program\ files/microchip/mplab\ c30/include/stdlib.h c:/program\ files/microchip/mplab\ c30/include/yvals.h c:/program\ files/microchip/mplab\ c30/include/stdio.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24FJ64GA002.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24Fxxxx.h C:/Microchip\ Solutions/Microchip/Include/Compiler.h C:/Microchip\ Solutions/Microchip/MDD\ File\ System/SD-SPI.c
	$(CC) -mcpu=24FJ64GA002 -x c -c "C:\Microchip Solutions\Microchip\MDD File System\SD-SPI.c" -o"SD-SPI.o" -I"C:\Microchip Solutions\Microchip\Include\MDD File System" -I"C:\Microchip Solutions\Microchip\Include" -I"D:\Projects C\Ostanovki" -I"C:\osa" -g -fno-short-double -Wall

DEE\ Emulation\ 16-bit.o : DEE\ Emulation\ 16-bit.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24FJ64GA002.h c:/program\ files/microchip/mplab\ c30/support/PIC24F/h/p24Fxxxx.h DEE\ Emulation\ 16-bit.c
	$(CC) -mcpu=24FJ64GA002 -x c -c "DEE Emulation 16-bit.c" -o"DEE Emulation 16-bit.o" -I"C:\Microchip Solutions\Microchip\Include\MDD File System" -I"C:\Microchip Solutions\Microchip\Include" -I"D:\Projects C\Ostanovki" -I"C:\osa" -g -fno-short-double -Wall

Flash\ Operations.o : Flash\ Operations.s
	$(CC) -mcpu=24FJ64GA002 -c "Flash Operations.s" -o"Flash Operations.o" -Wa,-I"C:\Microchip Solutions\Microchip\Include\MDD File System",-I"C:\Microchip Solutions\Microchip\Include",-I"D:\Projects C\Ostanovki",-I"C:\osa",-g

clean : 
	$(RM) "Ostanovki.o" "FSIO.o" "osa.o" "SD-SPI.o" "DEE Emulation 16-bit.o" "Flash Operations.o" "Ostanovki.cof" "Ostanovki.hex"

