/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PLATFORM:     Microchip C30
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                10   // Number of tasks that can be active at one time
#define OS_DISABLE_PRIORITY         // 


//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_TTIMERS           // Enable task timers (OS_Delay and OS_xxx_Wait_TO)
#define OS_USE_INLINE_TIMER         // Make OS_Timer service as in-line function


//------------------------------------------------------------------------------
// INTERRUPT SERVICES
//------------------------------------------------------------------------------

#define OS_ENABLE_INT_BSEM


#define OS_MSG_TYPE            const char *
//------------------------------------------------------------------------------
// BSEMS
//------------------------------------------------------------------------------

#define OS_BSEMS                7   // Number of binary semaphores

enum OSA_BSEMS_ENUM
{
    BS_GPRMC,
    BS_GPS_STR_L,
    BS_PLAY,
    BS_BUF1_DONE,
    BS_BUF2_DONE,
	BS_DING_PLAY,
	BS_INDIK_REFRESH,
};




#endif
